plugins:
  - babel

env:
  browser: true

parser: babel-eslint

extends:
  - "airbnb-base"

rules:
  no-console: 0
  import/extensions: 0
  import/prefer-default-export: 0
  no-param-reassign: 0
